---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - critical
  - default
  - import_files
  - low

# Configure Sidekiq to use Redis URL from the environment variable
:redis:
  :url: <%= ENV['REDIS_URL'] %>